### ISSUE TITLE
Error on 'create a database and populate it with data'

### ISSUE THREAD

**Issue by runout-at** [FunkFeuer/common-node-db#1]
running `python active/www/app/deploy.py app create -apply_to_version active`
gives:
```
Traceback (most recent call last):
  File "active/www/app/deploy.py", line 83, in <module>
    command ()
  File "/home/ffm/active/tapyr/_TFL/Command.py", line 383, in __call__
    return self._cmd (_argv, ** _kw)
  File "/home/ffm/active/tapyr/_TFL/CAO.py", line 1786, in __call__
    return cao (* handler_args, ** handler_kw)
  File "/home/ffm/active/tapyr/_TFL/CAO.py", line 2041, in __call__
    return handler (self, * args, ** kw)
  File "/home/ffm/active/tapyr/_TFL/Command.py", line 487, in _wrapped_handler
    return self.handler (cao, * args, ** kw)
  File "/home/ffm/active/tapyr/_TFL/Command.py", line 519, in handler
    return self._handler (cao)
  File "/home/ffm/active/tapyr/_GTW/deploy.py", line 283, in _handle_app
    self._app_call (cao, P, app, args)
  File "/home/ffm/active/tapyr/_GTW/deploy.py", line 261, in _app_call
    print (app (* args))
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/base.py", line 95, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/base.py", line 225, in run
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/base.py", line 187, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/processes.py", line 206, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/machines/base.py", line 22, in verify
    stdout, stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: [u'/usr/bin/python', u'-O', u'/home/ffm/active/www/app/model.py', u'create']
Exit code: 1
Stderr:  | Traceback (most recent call last):
         |   File "/home/ffm/active/www/app/model.py", line 85, in <module>
         |     import _GTW._OMP._Auth.Nav
         | ImportError: No module named Nav
```

Note: I'm still on the directory structure (ffm) of an old version but did all the steps from this site now.
System: Debian Stretch

**Comment by runout-at** [comment]
this error i could solve by purging the app directory and pulling the 'wien'-related repo again.
